### ISSUE TITLE
ta funcionando? posso copiar?

### ISSUE THREAD

**Issue by renato-macedo** [Santiael/compiler-project#1]

**Comment by santiael** [comment]
Falta bastante coisa pra dizer categoricamente que funciona. Recomendo apenas que utilize o código do parser e do scanner, o resto está bem precário.

**Comment by renato-macedo** [comment]
João ajudou?

**Comment by Santiael** [comment]
Nem um pouco kkkkkkkk

**Comment by santiael** [comment]
Prefiro não comentar...
